// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_to_server.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5fto_5fserver_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_5fto_5fserver_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_5fto_5fserver_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5fto_5fserver_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_client_5fto_5fserver_2eproto;
namespace SyncCloudDrive {
class CAddDirectory;
struct CAddDirectoryDefaultTypeInternal;
extern CAddDirectoryDefaultTypeInternal _CAddDirectory_default_instance_;
class CDeleteDirectory;
struct CDeleteDirectoryDefaultTypeInternal;
extern CDeleteDirectoryDefaultTypeInternal _CDeleteDirectory_default_instance_;
class CDeleteFile;
struct CDeleteFileDefaultTypeInternal;
extern CDeleteFileDefaultTypeInternal _CDeleteFile_default_instance_;
class CDownLoad;
struct CDownLoadDefaultTypeInternal;
extern CDownLoadDefaultTypeInternal _CDownLoad_default_instance_;
class CLogin;
struct CLoginDefaultTypeInternal;
extern CLoginDefaultTypeInternal _CLogin_default_instance_;
class CModifyUser;
struct CModifyUserDefaultTypeInternal;
extern CModifyUserDefaultTypeInternal _CModifyUser_default_instance_;
class CRegister;
struct CRegisterDefaultTypeInternal;
extern CRegisterDefaultTypeInternal _CRegister_default_instance_;
class CUploadData;
struct CUploadDataDefaultTypeInternal;
extern CUploadDataDefaultTypeInternal _CUploadData_default_instance_;
class CUploadFile;
struct CUploadFileDefaultTypeInternal;
extern CUploadFileDefaultTypeInternal _CUploadFile_default_instance_;
}  // namespace SyncCloudDrive
PROTOBUF_NAMESPACE_OPEN
template<> ::SyncCloudDrive::CAddDirectory* Arena::CreateMaybeMessage<::SyncCloudDrive::CAddDirectory>(Arena*);
template<> ::SyncCloudDrive::CDeleteDirectory* Arena::CreateMaybeMessage<::SyncCloudDrive::CDeleteDirectory>(Arena*);
template<> ::SyncCloudDrive::CDeleteFile* Arena::CreateMaybeMessage<::SyncCloudDrive::CDeleteFile>(Arena*);
template<> ::SyncCloudDrive::CDownLoad* Arena::CreateMaybeMessage<::SyncCloudDrive::CDownLoad>(Arena*);
template<> ::SyncCloudDrive::CLogin* Arena::CreateMaybeMessage<::SyncCloudDrive::CLogin>(Arena*);
template<> ::SyncCloudDrive::CModifyUser* Arena::CreateMaybeMessage<::SyncCloudDrive::CModifyUser>(Arena*);
template<> ::SyncCloudDrive::CRegister* Arena::CreateMaybeMessage<::SyncCloudDrive::CRegister>(Arena*);
template<> ::SyncCloudDrive::CUploadData* Arena::CreateMaybeMessage<::SyncCloudDrive::CUploadData>(Arena*);
template<> ::SyncCloudDrive::CUploadFile* Arena::CreateMaybeMessage<::SyncCloudDrive::CUploadFile>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SyncCloudDrive {

enum ClientCommandType : int {
  C_REGISTER = 0,
  C_LOGIN = 1,
  C_SYNC = 2,
  C_UPLOAD_FILE = 3,
  C_DOWNLOAD = 4,
  C_UPLOAD_DATA = 5,
  C_DELETE_FILE = 6,
  C_ADD_DIRECTORY = 7,
  C_DELETE_DIRECTORY = 8,
  C_MODIFY_USER = 9,
  ClientCommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ClientCommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ClientCommandType_IsValid(int value);
constexpr ClientCommandType ClientCommandType_MIN = C_REGISTER;
constexpr ClientCommandType ClientCommandType_MAX = C_MODIFY_USER;
constexpr int ClientCommandType_ARRAYSIZE = ClientCommandType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ClientCommandType_descriptor();
template<typename T>
inline const std::string& ClientCommandType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ClientCommandType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ClientCommandType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ClientCommandType_descriptor(), enum_t_value);
}
inline bool ClientCommandType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ClientCommandType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ClientCommandType>(
    ClientCommandType_descriptor(), name, value);
}
// ===================================================================

class CRegister final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CRegister) */ {
 public:
  inline CRegister() : CRegister(nullptr) {}
  ~CRegister() override;
  explicit PROTOBUF_CONSTEXPR CRegister(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CRegister(const CRegister& from);
  CRegister(CRegister&& from) noexcept
    : CRegister() {
    *this = ::std::move(from);
  }

  inline CRegister& operator=(const CRegister& from) {
    CopyFrom(from);
    return *this;
  }
  inline CRegister& operator=(CRegister&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CRegister& default_instance() {
    return *internal_default_instance();
  }
  static inline const CRegister* internal_default_instance() {
    return reinterpret_cast<const CRegister*>(
               &_CRegister_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CRegister& a, CRegister& b) {
    a.Swap(&b);
  }
  inline void Swap(CRegister* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CRegister* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CRegister* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CRegister>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CRegister& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CRegister& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CRegister* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CRegister";
  }
  protected:
  explicit CRegister(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPasswordMd5FieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string password_md5 = 2;
  void clear_password_md5();
  const std::string& password_md5() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password_md5(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password_md5();
  PROTOBUF_NODISCARD std::string* release_password_md5();
  void set_allocated_password_md5(std::string* password_md5);
  private:
  const std::string& _internal_password_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password_md5(const std::string& value);
  std::string* _internal_mutable_password_md5();
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CRegister)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_md5_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// -------------------------------------------------------------------

class CLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CLogin) */ {
 public:
  inline CLogin() : CLogin(nullptr) {}
  ~CLogin() override;
  explicit PROTOBUF_CONSTEXPR CLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CLogin(const CLogin& from);
  CLogin(CLogin&& from) noexcept
    : CLogin() {
    *this = ::std::move(from);
  }

  inline CLogin& operator=(const CLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline CLogin& operator=(CLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const CLogin* internal_default_instance() {
    return reinterpret_cast<const CLogin*>(
               &_CLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CLogin& a, CLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(CLogin* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CLogin>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CLogin& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CLogin& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CLogin* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CLogin";
  }
  protected:
  explicit CLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPasswordMd5FieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string password_md5 = 2;
  void clear_password_md5();
  const std::string& password_md5() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password_md5(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password_md5();
  PROTOBUF_NODISCARD std::string* release_password_md5();
  void set_allocated_password_md5(std::string* password_md5);
  private:
  const std::string& _internal_password_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password_md5(const std::string& value);
  std::string* _internal_mutable_password_md5();
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_md5_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// -------------------------------------------------------------------

class CUploadFile final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CUploadFile) */ {
 public:
  inline CUploadFile() : CUploadFile(nullptr) {}
  ~CUploadFile() override;
  explicit PROTOBUF_CONSTEXPR CUploadFile(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CUploadFile(const CUploadFile& from);
  CUploadFile(CUploadFile&& from) noexcept
    : CUploadFile() {
    *this = ::std::move(from);
  }

  inline CUploadFile& operator=(const CUploadFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline CUploadFile& operator=(CUploadFile&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CUploadFile& default_instance() {
    return *internal_default_instance();
  }
  static inline const CUploadFile* internal_default_instance() {
    return reinterpret_cast<const CUploadFile*>(
               &_CUploadFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CUploadFile& a, CUploadFile& b) {
    a.Swap(&b);
  }
  inline void Swap(CUploadFile* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CUploadFile* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CUploadFile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CUploadFile>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CUploadFile& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CUploadFile& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CUploadFile* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CUploadFile";
  }
  protected:
  explicit CUploadFile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMd5FieldNumber = 1,
    kNameFieldNumber = 2,
    kParentIdFieldNumber = 4,
    kSizeFieldNumber = 3,
    kNoFieldNumber = 5,
  };
  // string md5 = 1;
  void clear_md5();
  const std::string& md5() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_md5(ArgT0&& arg0, ArgT... args);
  std::string* mutable_md5();
  PROTOBUF_NODISCARD std::string* release_md5();
  void set_allocated_md5(std::string* md5);
  private:
  const std::string& _internal_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_md5(const std::string& value);
  std::string* _internal_mutable_md5();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string parent_id = 4;
  void clear_parent_id();
  const std::string& parent_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_parent_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_parent_id();
  PROTOBUF_NODISCARD std::string* release_parent_id();
  void set_allocated_parent_id(std::string* parent_id);
  private:
  const std::string& _internal_parent_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_parent_id(const std::string& value);
  std::string* _internal_mutable_parent_id();
  public:

  // int32 size = 3;
  void clear_size();
  int32_t size() const;
  void set_size(int32_t value);
  private:
  int32_t _internal_size() const;
  void _internal_set_size(int32_t value);
  public:

  // int32 no = 5;
  void clear_no();
  int32_t no() const;
  void set_no(int32_t value);
  private:
  int32_t _internal_no() const;
  void _internal_set_no(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CUploadFile)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr md5_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr parent_id_;
  int32_t size_;
  int32_t no_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// -------------------------------------------------------------------

class CDownLoad final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CDownLoad) */ {
 public:
  inline CDownLoad() : CDownLoad(nullptr) {}
  ~CDownLoad() override;
  explicit PROTOBUF_CONSTEXPR CDownLoad(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CDownLoad(const CDownLoad& from);
  CDownLoad(CDownLoad&& from) noexcept
    : CDownLoad() {
    *this = ::std::move(from);
  }

  inline CDownLoad& operator=(const CDownLoad& from) {
    CopyFrom(from);
    return *this;
  }
  inline CDownLoad& operator=(CDownLoad&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CDownLoad& default_instance() {
    return *internal_default_instance();
  }
  static inline const CDownLoad* internal_default_instance() {
    return reinterpret_cast<const CDownLoad*>(
               &_CDownLoad_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CDownLoad& a, CDownLoad& b) {
    a.Swap(&b);
  }
  inline void Swap(CDownLoad* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CDownLoad* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CDownLoad* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CDownLoad>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CDownLoad& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CDownLoad& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CDownLoad* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CDownLoad";
  }
  protected:
  explicit CDownLoad(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileIdFieldNumber = 1,
    kSlideNoFieldNumber = 2,
  };
  // string file_id = 1;
  void clear_file_id();
  const std::string& file_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_id();
  PROTOBUF_NODISCARD std::string* release_file_id();
  void set_allocated_file_id(std::string* file_id);
  private:
  const std::string& _internal_file_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_id(const std::string& value);
  std::string* _internal_mutable_file_id();
  public:

  // int32 slide_no = 2;
  void clear_slide_no();
  int32_t slide_no() const;
  void set_slide_no(int32_t value);
  private:
  int32_t _internal_slide_no() const;
  void _internal_set_slide_no(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CDownLoad)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_id_;
  int32_t slide_no_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// -------------------------------------------------------------------

class CUploadData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CUploadData) */ {
 public:
  inline CUploadData() : CUploadData(nullptr) {}
  ~CUploadData() override;
  explicit PROTOBUF_CONSTEXPR CUploadData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CUploadData(const CUploadData& from);
  CUploadData(CUploadData&& from) noexcept
    : CUploadData() {
    *this = ::std::move(from);
  }

  inline CUploadData& operator=(const CUploadData& from) {
    CopyFrom(from);
    return *this;
  }
  inline CUploadData& operator=(CUploadData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CUploadData& default_instance() {
    return *internal_default_instance();
  }
  static inline const CUploadData* internal_default_instance() {
    return reinterpret_cast<const CUploadData*>(
               &_CUploadData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CUploadData& a, CUploadData& b) {
    a.Swap(&b);
  }
  inline void Swap(CUploadData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CUploadData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CUploadData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CUploadData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CUploadData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CUploadData& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CUploadData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CUploadData";
  }
  protected:
  explicit CUploadData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMd5FieldNumber = 1,
    kDataFieldNumber = 3,
    kSlideNoFieldNumber = 2,
    kNoFieldNumber = 4,
  };
  // string md5 = 1;
  void clear_md5();
  const std::string& md5() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_md5(ArgT0&& arg0, ArgT... args);
  std::string* mutable_md5();
  PROTOBUF_NODISCARD std::string* release_md5();
  void set_allocated_md5(std::string* md5);
  private:
  const std::string& _internal_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_md5(const std::string& value);
  std::string* _internal_mutable_md5();
  public:

  // string data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 slide_no = 2;
  void clear_slide_no();
  int32_t slide_no() const;
  void set_slide_no(int32_t value);
  private:
  int32_t _internal_slide_no() const;
  void _internal_set_slide_no(int32_t value);
  public:

  // int32 no = 4;
  void clear_no();
  int32_t no() const;
  void set_no(int32_t value);
  private:
  int32_t _internal_no() const;
  void _internal_set_no(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CUploadData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr md5_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  int32_t slide_no_;
  int32_t no_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// -------------------------------------------------------------------

class CDeleteFile final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CDeleteFile) */ {
 public:
  inline CDeleteFile() : CDeleteFile(nullptr) {}
  ~CDeleteFile() override;
  explicit PROTOBUF_CONSTEXPR CDeleteFile(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CDeleteFile(const CDeleteFile& from);
  CDeleteFile(CDeleteFile&& from) noexcept
    : CDeleteFile() {
    *this = ::std::move(from);
  }

  inline CDeleteFile& operator=(const CDeleteFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline CDeleteFile& operator=(CDeleteFile&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CDeleteFile& default_instance() {
    return *internal_default_instance();
  }
  static inline const CDeleteFile* internal_default_instance() {
    return reinterpret_cast<const CDeleteFile*>(
               &_CDeleteFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(CDeleteFile& a, CDeleteFile& b) {
    a.Swap(&b);
  }
  inline void Swap(CDeleteFile* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CDeleteFile* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CDeleteFile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CDeleteFile>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CDeleteFile& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CDeleteFile& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CDeleteFile* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CDeleteFile";
  }
  protected:
  explicit CDeleteFile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileIdFieldNumber = 1,
  };
  // string file_id = 1;
  void clear_file_id();
  const std::string& file_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_id();
  PROTOBUF_NODISCARD std::string* release_file_id();
  void set_allocated_file_id(std::string* file_id);
  private:
  const std::string& _internal_file_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_id(const std::string& value);
  std::string* _internal_mutable_file_id();
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CDeleteFile)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// -------------------------------------------------------------------

class CAddDirectory final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CAddDirectory) */ {
 public:
  inline CAddDirectory() : CAddDirectory(nullptr) {}
  ~CAddDirectory() override;
  explicit PROTOBUF_CONSTEXPR CAddDirectory(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CAddDirectory(const CAddDirectory& from);
  CAddDirectory(CAddDirectory&& from) noexcept
    : CAddDirectory() {
    *this = ::std::move(from);
  }

  inline CAddDirectory& operator=(const CAddDirectory& from) {
    CopyFrom(from);
    return *this;
  }
  inline CAddDirectory& operator=(CAddDirectory&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CAddDirectory& default_instance() {
    return *internal_default_instance();
  }
  static inline const CAddDirectory* internal_default_instance() {
    return reinterpret_cast<const CAddDirectory*>(
               &_CAddDirectory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(CAddDirectory& a, CAddDirectory& b) {
    a.Swap(&b);
  }
  inline void Swap(CAddDirectory* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CAddDirectory* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CAddDirectory* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CAddDirectory>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CAddDirectory& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CAddDirectory& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CAddDirectory* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CAddDirectory";
  }
  protected:
  explicit CAddDirectory(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParentIdFieldNumber = 1,
    kNameFieldNumber = 2,
  };
  // string parent_id = 1;
  void clear_parent_id();
  const std::string& parent_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_parent_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_parent_id();
  PROTOBUF_NODISCARD std::string* release_parent_id();
  void set_allocated_parent_id(std::string* parent_id);
  private:
  const std::string& _internal_parent_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_parent_id(const std::string& value);
  std::string* _internal_mutable_parent_id();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CAddDirectory)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr parent_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// -------------------------------------------------------------------

class CDeleteDirectory final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CDeleteDirectory) */ {
 public:
  inline CDeleteDirectory() : CDeleteDirectory(nullptr) {}
  ~CDeleteDirectory() override;
  explicit PROTOBUF_CONSTEXPR CDeleteDirectory(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CDeleteDirectory(const CDeleteDirectory& from);
  CDeleteDirectory(CDeleteDirectory&& from) noexcept
    : CDeleteDirectory() {
    *this = ::std::move(from);
  }

  inline CDeleteDirectory& operator=(const CDeleteDirectory& from) {
    CopyFrom(from);
    return *this;
  }
  inline CDeleteDirectory& operator=(CDeleteDirectory&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CDeleteDirectory& default_instance() {
    return *internal_default_instance();
  }
  static inline const CDeleteDirectory* internal_default_instance() {
    return reinterpret_cast<const CDeleteDirectory*>(
               &_CDeleteDirectory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(CDeleteDirectory& a, CDeleteDirectory& b) {
    a.Swap(&b);
  }
  inline void Swap(CDeleteDirectory* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CDeleteDirectory* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CDeleteDirectory* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CDeleteDirectory>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CDeleteDirectory& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CDeleteDirectory& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CDeleteDirectory* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CDeleteDirectory";
  }
  protected:
  explicit CDeleteDirectory(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDirectoryIdFieldNumber = 1,
  };
  // string directory_id = 1;
  void clear_directory_id();
  const std::string& directory_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_directory_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_directory_id();
  PROTOBUF_NODISCARD std::string* release_directory_id();
  void set_allocated_directory_id(std::string* directory_id);
  private:
  const std::string& _internal_directory_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_directory_id(const std::string& value);
  std::string* _internal_mutable_directory_id();
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CDeleteDirectory)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr directory_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// -------------------------------------------------------------------

class CModifyUser final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.CModifyUser) */ {
 public:
  inline CModifyUser() : CModifyUser(nullptr) {}
  ~CModifyUser() override;
  explicit PROTOBUF_CONSTEXPR CModifyUser(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CModifyUser(const CModifyUser& from);
  CModifyUser(CModifyUser&& from) noexcept
    : CModifyUser() {
    *this = ::std::move(from);
  }

  inline CModifyUser& operator=(const CModifyUser& from) {
    CopyFrom(from);
    return *this;
  }
  inline CModifyUser& operator=(CModifyUser&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CModifyUser& default_instance() {
    return *internal_default_instance();
  }
  static inline const CModifyUser* internal_default_instance() {
    return reinterpret_cast<const CModifyUser*>(
               &_CModifyUser_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(CModifyUser& a, CModifyUser& b) {
    a.Swap(&b);
  }
  inline void Swap(CModifyUser* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CModifyUser* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CModifyUser* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CModifyUser>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CModifyUser& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CModifyUser& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CModifyUser* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.CModifyUser";
  }
  protected:
  explicit CModifyUser(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // string content = 2;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // int32 type = 1;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.CModifyUser)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  int32_t type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fto_5fserver_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CRegister

// string name = 1;
inline void CRegister::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& CRegister::name() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CRegister.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CRegister::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CRegister.name)
}
inline std::string* CRegister::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CRegister.name)
  return _s;
}
inline const std::string& CRegister::_internal_name() const {
  return name_.Get();
}
inline void CRegister::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* CRegister::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* CRegister::release_name() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CRegister.name)
  return name_.Release();
}
inline void CRegister::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CRegister.name)
}

// string password_md5 = 2;
inline void CRegister::clear_password_md5() {
  password_md5_.ClearToEmpty();
}
inline const std::string& CRegister::password_md5() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CRegister.password_md5)
  return _internal_password_md5();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CRegister::set_password_md5(ArgT0&& arg0, ArgT... args) {
 
 password_md5_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CRegister.password_md5)
}
inline std::string* CRegister::mutable_password_md5() {
  std::string* _s = _internal_mutable_password_md5();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CRegister.password_md5)
  return _s;
}
inline const std::string& CRegister::_internal_password_md5() const {
  return password_md5_.Get();
}
inline void CRegister::_internal_set_password_md5(const std::string& value) {
  
  password_md5_.Set(value, GetArenaForAllocation());
}
inline std::string* CRegister::_internal_mutable_password_md5() {
  
  return password_md5_.Mutable(GetArenaForAllocation());
}
inline std::string* CRegister::release_password_md5() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CRegister.password_md5)
  return password_md5_.Release();
}
inline void CRegister::set_allocated_password_md5(std::string* password_md5) {
  if (password_md5 != nullptr) {
    
  } else {
    
  }
  password_md5_.SetAllocated(password_md5, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_md5_.IsDefault()) {
    password_md5_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CRegister.password_md5)
}

// -------------------------------------------------------------------

// CLogin

// string name = 1;
inline void CLogin::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& CLogin::name() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CLogin.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CLogin::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CLogin.name)
}
inline std::string* CLogin::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CLogin.name)
  return _s;
}
inline const std::string& CLogin::_internal_name() const {
  return name_.Get();
}
inline void CLogin::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* CLogin::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* CLogin::release_name() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CLogin.name)
  return name_.Release();
}
inline void CLogin::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CLogin.name)
}

// string password_md5 = 2;
inline void CLogin::clear_password_md5() {
  password_md5_.ClearToEmpty();
}
inline const std::string& CLogin::password_md5() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CLogin.password_md5)
  return _internal_password_md5();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CLogin::set_password_md5(ArgT0&& arg0, ArgT... args) {
 
 password_md5_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CLogin.password_md5)
}
inline std::string* CLogin::mutable_password_md5() {
  std::string* _s = _internal_mutable_password_md5();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CLogin.password_md5)
  return _s;
}
inline const std::string& CLogin::_internal_password_md5() const {
  return password_md5_.Get();
}
inline void CLogin::_internal_set_password_md5(const std::string& value) {
  
  password_md5_.Set(value, GetArenaForAllocation());
}
inline std::string* CLogin::_internal_mutable_password_md5() {
  
  return password_md5_.Mutable(GetArenaForAllocation());
}
inline std::string* CLogin::release_password_md5() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CLogin.password_md5)
  return password_md5_.Release();
}
inline void CLogin::set_allocated_password_md5(std::string* password_md5) {
  if (password_md5 != nullptr) {
    
  } else {
    
  }
  password_md5_.SetAllocated(password_md5, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_md5_.IsDefault()) {
    password_md5_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CLogin.password_md5)
}

// -------------------------------------------------------------------

// CUploadFile

// string md5 = 1;
inline void CUploadFile::clear_md5() {
  md5_.ClearToEmpty();
}
inline const std::string& CUploadFile::md5() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadFile.md5)
  return _internal_md5();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CUploadFile::set_md5(ArgT0&& arg0, ArgT... args) {
 
 md5_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadFile.md5)
}
inline std::string* CUploadFile::mutable_md5() {
  std::string* _s = _internal_mutable_md5();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CUploadFile.md5)
  return _s;
}
inline const std::string& CUploadFile::_internal_md5() const {
  return md5_.Get();
}
inline void CUploadFile::_internal_set_md5(const std::string& value) {
  
  md5_.Set(value, GetArenaForAllocation());
}
inline std::string* CUploadFile::_internal_mutable_md5() {
  
  return md5_.Mutable(GetArenaForAllocation());
}
inline std::string* CUploadFile::release_md5() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CUploadFile.md5)
  return md5_.Release();
}
inline void CUploadFile::set_allocated_md5(std::string* md5) {
  if (md5 != nullptr) {
    
  } else {
    
  }
  md5_.SetAllocated(md5, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (md5_.IsDefault()) {
    md5_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CUploadFile.md5)
}

// string name = 2;
inline void CUploadFile::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& CUploadFile::name() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadFile.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CUploadFile::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadFile.name)
}
inline std::string* CUploadFile::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CUploadFile.name)
  return _s;
}
inline const std::string& CUploadFile::_internal_name() const {
  return name_.Get();
}
inline void CUploadFile::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* CUploadFile::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* CUploadFile::release_name() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CUploadFile.name)
  return name_.Release();
}
inline void CUploadFile::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CUploadFile.name)
}

// int32 size = 3;
inline void CUploadFile::clear_size() {
  size_ = 0;
}
inline int32_t CUploadFile::_internal_size() const {
  return size_;
}
inline int32_t CUploadFile::size() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadFile.size)
  return _internal_size();
}
inline void CUploadFile::_internal_set_size(int32_t value) {
  
  size_ = value;
}
inline void CUploadFile::set_size(int32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadFile.size)
}

// string parent_id = 4;
inline void CUploadFile::clear_parent_id() {
  parent_id_.ClearToEmpty();
}
inline const std::string& CUploadFile::parent_id() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadFile.parent_id)
  return _internal_parent_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CUploadFile::set_parent_id(ArgT0&& arg0, ArgT... args) {
 
 parent_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadFile.parent_id)
}
inline std::string* CUploadFile::mutable_parent_id() {
  std::string* _s = _internal_mutable_parent_id();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CUploadFile.parent_id)
  return _s;
}
inline const std::string& CUploadFile::_internal_parent_id() const {
  return parent_id_.Get();
}
inline void CUploadFile::_internal_set_parent_id(const std::string& value) {
  
  parent_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CUploadFile::_internal_mutable_parent_id() {
  
  return parent_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CUploadFile::release_parent_id() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CUploadFile.parent_id)
  return parent_id_.Release();
}
inline void CUploadFile::set_allocated_parent_id(std::string* parent_id) {
  if (parent_id != nullptr) {
    
  } else {
    
  }
  parent_id_.SetAllocated(parent_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (parent_id_.IsDefault()) {
    parent_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CUploadFile.parent_id)
}

// int32 no = 5;
inline void CUploadFile::clear_no() {
  no_ = 0;
}
inline int32_t CUploadFile::_internal_no() const {
  return no_;
}
inline int32_t CUploadFile::no() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadFile.no)
  return _internal_no();
}
inline void CUploadFile::_internal_set_no(int32_t value) {
  
  no_ = value;
}
inline void CUploadFile::set_no(int32_t value) {
  _internal_set_no(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadFile.no)
}

// -------------------------------------------------------------------

// CDownLoad

// string file_id = 1;
inline void CDownLoad::clear_file_id() {
  file_id_.ClearToEmpty();
}
inline const std::string& CDownLoad::file_id() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CDownLoad.file_id)
  return _internal_file_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CDownLoad::set_file_id(ArgT0&& arg0, ArgT... args) {
 
 file_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CDownLoad.file_id)
}
inline std::string* CDownLoad::mutable_file_id() {
  std::string* _s = _internal_mutable_file_id();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CDownLoad.file_id)
  return _s;
}
inline const std::string& CDownLoad::_internal_file_id() const {
  return file_id_.Get();
}
inline void CDownLoad::_internal_set_file_id(const std::string& value) {
  
  file_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CDownLoad::_internal_mutable_file_id() {
  
  return file_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CDownLoad::release_file_id() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CDownLoad.file_id)
  return file_id_.Release();
}
inline void CDownLoad::set_allocated_file_id(std::string* file_id) {
  if (file_id != nullptr) {
    
  } else {
    
  }
  file_id_.SetAllocated(file_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (file_id_.IsDefault()) {
    file_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CDownLoad.file_id)
}

// int32 slide_no = 2;
inline void CDownLoad::clear_slide_no() {
  slide_no_ = 0;
}
inline int32_t CDownLoad::_internal_slide_no() const {
  return slide_no_;
}
inline int32_t CDownLoad::slide_no() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CDownLoad.slide_no)
  return _internal_slide_no();
}
inline void CDownLoad::_internal_set_slide_no(int32_t value) {
  
  slide_no_ = value;
}
inline void CDownLoad::set_slide_no(int32_t value) {
  _internal_set_slide_no(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CDownLoad.slide_no)
}

// -------------------------------------------------------------------

// CUploadData

// string md5 = 1;
inline void CUploadData::clear_md5() {
  md5_.ClearToEmpty();
}
inline const std::string& CUploadData::md5() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadData.md5)
  return _internal_md5();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CUploadData::set_md5(ArgT0&& arg0, ArgT... args) {
 
 md5_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadData.md5)
}
inline std::string* CUploadData::mutable_md5() {
  std::string* _s = _internal_mutable_md5();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CUploadData.md5)
  return _s;
}
inline const std::string& CUploadData::_internal_md5() const {
  return md5_.Get();
}
inline void CUploadData::_internal_set_md5(const std::string& value) {
  
  md5_.Set(value, GetArenaForAllocation());
}
inline std::string* CUploadData::_internal_mutable_md5() {
  
  return md5_.Mutable(GetArenaForAllocation());
}
inline std::string* CUploadData::release_md5() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CUploadData.md5)
  return md5_.Release();
}
inline void CUploadData::set_allocated_md5(std::string* md5) {
  if (md5 != nullptr) {
    
  } else {
    
  }
  md5_.SetAllocated(md5, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (md5_.IsDefault()) {
    md5_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CUploadData.md5)
}

// int32 slide_no = 2;
inline void CUploadData::clear_slide_no() {
  slide_no_ = 0;
}
inline int32_t CUploadData::_internal_slide_no() const {
  return slide_no_;
}
inline int32_t CUploadData::slide_no() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadData.slide_no)
  return _internal_slide_no();
}
inline void CUploadData::_internal_set_slide_no(int32_t value) {
  
  slide_no_ = value;
}
inline void CUploadData::set_slide_no(int32_t value) {
  _internal_set_slide_no(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadData.slide_no)
}

// string data = 3;
inline void CUploadData::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& CUploadData::data() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadData.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CUploadData::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadData.data)
}
inline std::string* CUploadData::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CUploadData.data)
  return _s;
}
inline const std::string& CUploadData::_internal_data() const {
  return data_.Get();
}
inline void CUploadData::_internal_set_data(const std::string& value) {
  
  data_.Set(value, GetArenaForAllocation());
}
inline std::string* CUploadData::_internal_mutable_data() {
  
  return data_.Mutable(GetArenaForAllocation());
}
inline std::string* CUploadData::release_data() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CUploadData.data)
  return data_.Release();
}
inline void CUploadData::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault()) {
    data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CUploadData.data)
}

// int32 no = 4;
inline void CUploadData::clear_no() {
  no_ = 0;
}
inline int32_t CUploadData::_internal_no() const {
  return no_;
}
inline int32_t CUploadData::no() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CUploadData.no)
  return _internal_no();
}
inline void CUploadData::_internal_set_no(int32_t value) {
  
  no_ = value;
}
inline void CUploadData::set_no(int32_t value) {
  _internal_set_no(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CUploadData.no)
}

// -------------------------------------------------------------------

// CDeleteFile

// string file_id = 1;
inline void CDeleteFile::clear_file_id() {
  file_id_.ClearToEmpty();
}
inline const std::string& CDeleteFile::file_id() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CDeleteFile.file_id)
  return _internal_file_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CDeleteFile::set_file_id(ArgT0&& arg0, ArgT... args) {
 
 file_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CDeleteFile.file_id)
}
inline std::string* CDeleteFile::mutable_file_id() {
  std::string* _s = _internal_mutable_file_id();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CDeleteFile.file_id)
  return _s;
}
inline const std::string& CDeleteFile::_internal_file_id() const {
  return file_id_.Get();
}
inline void CDeleteFile::_internal_set_file_id(const std::string& value) {
  
  file_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CDeleteFile::_internal_mutable_file_id() {
  
  return file_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CDeleteFile::release_file_id() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CDeleteFile.file_id)
  return file_id_.Release();
}
inline void CDeleteFile::set_allocated_file_id(std::string* file_id) {
  if (file_id != nullptr) {
    
  } else {
    
  }
  file_id_.SetAllocated(file_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (file_id_.IsDefault()) {
    file_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CDeleteFile.file_id)
}

// -------------------------------------------------------------------

// CAddDirectory

// string parent_id = 1;
inline void CAddDirectory::clear_parent_id() {
  parent_id_.ClearToEmpty();
}
inline const std::string& CAddDirectory::parent_id() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CAddDirectory.parent_id)
  return _internal_parent_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CAddDirectory::set_parent_id(ArgT0&& arg0, ArgT... args) {
 
 parent_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CAddDirectory.parent_id)
}
inline std::string* CAddDirectory::mutable_parent_id() {
  std::string* _s = _internal_mutable_parent_id();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CAddDirectory.parent_id)
  return _s;
}
inline const std::string& CAddDirectory::_internal_parent_id() const {
  return parent_id_.Get();
}
inline void CAddDirectory::_internal_set_parent_id(const std::string& value) {
  
  parent_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CAddDirectory::_internal_mutable_parent_id() {
  
  return parent_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CAddDirectory::release_parent_id() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CAddDirectory.parent_id)
  return parent_id_.Release();
}
inline void CAddDirectory::set_allocated_parent_id(std::string* parent_id) {
  if (parent_id != nullptr) {
    
  } else {
    
  }
  parent_id_.SetAllocated(parent_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (parent_id_.IsDefault()) {
    parent_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CAddDirectory.parent_id)
}

// string name = 2;
inline void CAddDirectory::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& CAddDirectory::name() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CAddDirectory.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CAddDirectory::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CAddDirectory.name)
}
inline std::string* CAddDirectory::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CAddDirectory.name)
  return _s;
}
inline const std::string& CAddDirectory::_internal_name() const {
  return name_.Get();
}
inline void CAddDirectory::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* CAddDirectory::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* CAddDirectory::release_name() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CAddDirectory.name)
  return name_.Release();
}
inline void CAddDirectory::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CAddDirectory.name)
}

// -------------------------------------------------------------------

// CDeleteDirectory

// string directory_id = 1;
inline void CDeleteDirectory::clear_directory_id() {
  directory_id_.ClearToEmpty();
}
inline const std::string& CDeleteDirectory::directory_id() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CDeleteDirectory.directory_id)
  return _internal_directory_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CDeleteDirectory::set_directory_id(ArgT0&& arg0, ArgT... args) {
 
 directory_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CDeleteDirectory.directory_id)
}
inline std::string* CDeleteDirectory::mutable_directory_id() {
  std::string* _s = _internal_mutable_directory_id();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CDeleteDirectory.directory_id)
  return _s;
}
inline const std::string& CDeleteDirectory::_internal_directory_id() const {
  return directory_id_.Get();
}
inline void CDeleteDirectory::_internal_set_directory_id(const std::string& value) {
  
  directory_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CDeleteDirectory::_internal_mutable_directory_id() {
  
  return directory_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CDeleteDirectory::release_directory_id() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CDeleteDirectory.directory_id)
  return directory_id_.Release();
}
inline void CDeleteDirectory::set_allocated_directory_id(std::string* directory_id) {
  if (directory_id != nullptr) {
    
  } else {
    
  }
  directory_id_.SetAllocated(directory_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (directory_id_.IsDefault()) {
    directory_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CDeleteDirectory.directory_id)
}

// -------------------------------------------------------------------

// CModifyUser

// int32 type = 1;
inline void CModifyUser::clear_type() {
  type_ = 0;
}
inline int32_t CModifyUser::_internal_type() const {
  return type_;
}
inline int32_t CModifyUser::type() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CModifyUser.type)
  return _internal_type();
}
inline void CModifyUser::_internal_set_type(int32_t value) {
  
  type_ = value;
}
inline void CModifyUser::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CModifyUser.type)
}

// string content = 2;
inline void CModifyUser::clear_content() {
  content_.ClearToEmpty();
}
inline const std::string& CModifyUser::content() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.CModifyUser.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CModifyUser::set_content(ArgT0&& arg0, ArgT... args) {
 
 content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.CModifyUser.content)
}
inline std::string* CModifyUser::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.CModifyUser.content)
  return _s;
}
inline const std::string& CModifyUser::_internal_content() const {
  return content_.Get();
}
inline void CModifyUser::_internal_set_content(const std::string& value) {
  
  content_.Set(value, GetArenaForAllocation());
}
inline std::string* CModifyUser::_internal_mutable_content() {
  
  return content_.Mutable(GetArenaForAllocation());
}
inline std::string* CModifyUser::release_content() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.CModifyUser.content)
  return content_.Release();
}
inline void CModifyUser::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (content_.IsDefault()) {
    content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.CModifyUser.content)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SyncCloudDrive

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::SyncCloudDrive::ClientCommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SyncCloudDrive::ClientCommandType>() {
  return ::SyncCloudDrive::ClientCommandType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_5fto_5fserver_2eproto
