// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_to_client.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_server_5fto_5fclient_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_server_5fto_5fclient_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_server_5fto_5fclient_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_server_5fto_5fclient_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_server_5fto_5fclient_2eproto;
namespace SyncCloudDrive {
class SAddDirectory;
struct SAddDirectoryDefaultTypeInternal;
extern SAddDirectoryDefaultTypeInternal _SAddDirectory_default_instance_;
class SDeleteDirectory;
struct SDeleteDirectoryDefaultTypeInternal;
extern SDeleteDirectoryDefaultTypeInternal _SDeleteDirectory_default_instance_;
class SDeleteFile;
struct SDeleteFileDefaultTypeInternal;
extern SDeleteFileDefaultTypeInternal _SDeleteFile_default_instance_;
class SDownload;
struct SDownloadDefaultTypeInternal;
extern SDownloadDefaultTypeInternal _SDownload_default_instance_;
class SLogin;
struct SLoginDefaultTypeInternal;
extern SLoginDefaultTypeInternal _SLogin_default_instance_;
class SModifyUser;
struct SModifyUserDefaultTypeInternal;
extern SModifyUserDefaultTypeInternal _SModifyUser_default_instance_;
class SRegister;
struct SRegisterDefaultTypeInternal;
extern SRegisterDefaultTypeInternal _SRegister_default_instance_;
class SSync;
struct SSyncDefaultTypeInternal;
extern SSyncDefaultTypeInternal _SSync_default_instance_;
class SSync_Directory;
struct SSync_DirectoryDefaultTypeInternal;
extern SSync_DirectoryDefaultTypeInternal _SSync_Directory_default_instance_;
class SSync_File;
struct SSync_FileDefaultTypeInternal;
extern SSync_FileDefaultTypeInternal _SSync_File_default_instance_;
class SUploadFile;
struct SUploadFileDefaultTypeInternal;
extern SUploadFileDefaultTypeInternal _SUploadFile_default_instance_;
}  // namespace SyncCloudDrive
PROTOBUF_NAMESPACE_OPEN
template<> ::SyncCloudDrive::SAddDirectory* Arena::CreateMaybeMessage<::SyncCloudDrive::SAddDirectory>(Arena*);
template<> ::SyncCloudDrive::SDeleteDirectory* Arena::CreateMaybeMessage<::SyncCloudDrive::SDeleteDirectory>(Arena*);
template<> ::SyncCloudDrive::SDeleteFile* Arena::CreateMaybeMessage<::SyncCloudDrive::SDeleteFile>(Arena*);
template<> ::SyncCloudDrive::SDownload* Arena::CreateMaybeMessage<::SyncCloudDrive::SDownload>(Arena*);
template<> ::SyncCloudDrive::SLogin* Arena::CreateMaybeMessage<::SyncCloudDrive::SLogin>(Arena*);
template<> ::SyncCloudDrive::SModifyUser* Arena::CreateMaybeMessage<::SyncCloudDrive::SModifyUser>(Arena*);
template<> ::SyncCloudDrive::SRegister* Arena::CreateMaybeMessage<::SyncCloudDrive::SRegister>(Arena*);
template<> ::SyncCloudDrive::SSync* Arena::CreateMaybeMessage<::SyncCloudDrive::SSync>(Arena*);
template<> ::SyncCloudDrive::SSync_Directory* Arena::CreateMaybeMessage<::SyncCloudDrive::SSync_Directory>(Arena*);
template<> ::SyncCloudDrive::SSync_File* Arena::CreateMaybeMessage<::SyncCloudDrive::SSync_File>(Arena*);
template<> ::SyncCloudDrive::SUploadFile* Arena::CreateMaybeMessage<::SyncCloudDrive::SUploadFile>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SyncCloudDrive {

enum ServerCommandType : int {
  S_REGISTER = 0,
  S_LOGIN = 1,
  S_SYNC = 2,
  S_UPLOAD_FILE = 3,
  S_DOWNLOAD = 4,
  S_DELETE_FILE = 5,
  S_ADD_DIRECTORY = 6,
  S_DELETE_DIRECTORY = 7,
  S_MODIFY_USER = 8,
  ServerCommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ServerCommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ServerCommandType_IsValid(int value);
constexpr ServerCommandType ServerCommandType_MIN = S_REGISTER;
constexpr ServerCommandType ServerCommandType_MAX = S_MODIFY_USER;
constexpr int ServerCommandType_ARRAYSIZE = ServerCommandType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServerCommandType_descriptor();
template<typename T>
inline const std::string& ServerCommandType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ServerCommandType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ServerCommandType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ServerCommandType_descriptor(), enum_t_value);
}
inline bool ServerCommandType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServerCommandType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ServerCommandType>(
    ServerCommandType_descriptor(), name, value);
}
// ===================================================================

class SRegister final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SRegister) */ {
 public:
  inline SRegister() : SRegister(nullptr) {}
  ~SRegister() override;
  explicit PROTOBUF_CONSTEXPR SRegister(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SRegister(const SRegister& from);
  SRegister(SRegister&& from) noexcept
    : SRegister() {
    *this = ::std::move(from);
  }

  inline SRegister& operator=(const SRegister& from) {
    CopyFrom(from);
    return *this;
  }
  inline SRegister& operator=(SRegister&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SRegister& default_instance() {
    return *internal_default_instance();
  }
  static inline const SRegister* internal_default_instance() {
    return reinterpret_cast<const SRegister*>(
               &_SRegister_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SRegister& a, SRegister& b) {
    a.Swap(&b);
  }
  inline void Swap(SRegister* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SRegister* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SRegister* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SRegister>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SRegister& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SRegister& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SRegister* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SRegister";
  }
  protected:
  explicit SRegister(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // int32 state = 1;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SRegister)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SLogin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SLogin) */ {
 public:
  inline SLogin() : SLogin(nullptr) {}
  ~SLogin() override;
  explicit PROTOBUF_CONSTEXPR SLogin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SLogin(const SLogin& from);
  SLogin(SLogin&& from) noexcept
    : SLogin() {
    *this = ::std::move(from);
  }

  inline SLogin& operator=(const SLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline SLogin& operator=(SLogin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const SLogin* internal_default_instance() {
    return reinterpret_cast<const SLogin*>(
               &_SLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SLogin& a, SLogin& b) {
    a.Swap(&b);
  }
  inline void Swap(SLogin* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SLogin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SLogin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SLogin>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SLogin& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SLogin& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SLogin* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SLogin";
  }
  protected:
  explicit SLogin(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // int32 state = 1;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SLogin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SSync_File final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SSync.File) */ {
 public:
  inline SSync_File() : SSync_File(nullptr) {}
  ~SSync_File() override;
  explicit PROTOBUF_CONSTEXPR SSync_File(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SSync_File(const SSync_File& from);
  SSync_File(SSync_File&& from) noexcept
    : SSync_File() {
    *this = ::std::move(from);
  }

  inline SSync_File& operator=(const SSync_File& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSync_File& operator=(SSync_File&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SSync_File& default_instance() {
    return *internal_default_instance();
  }
  static inline const SSync_File* internal_default_instance() {
    return reinterpret_cast<const SSync_File*>(
               &_SSync_File_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SSync_File& a, SSync_File& b) {
    a.Swap(&b);
  }
  inline void Swap(SSync_File* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSync_File* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SSync_File* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SSync_File>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SSync_File& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SSync_File& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSync_File* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SSync.File";
  }
  protected:
  explicit SSync_File(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kNameFieldNumber = 2,
    kMd5FieldNumber = 3,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string md5 = 3;
  void clear_md5();
  const std::string& md5() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_md5(ArgT0&& arg0, ArgT... args);
  std::string* mutable_md5();
  PROTOBUF_NODISCARD std::string* release_md5();
  void set_allocated_md5(std::string* md5);
  private:
  const std::string& _internal_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_md5(const std::string& value);
  std::string* _internal_mutable_md5();
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SSync.File)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr md5_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SSync_Directory final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SSync.Directory) */ {
 public:
  inline SSync_Directory() : SSync_Directory(nullptr) {}
  ~SSync_Directory() override;
  explicit PROTOBUF_CONSTEXPR SSync_Directory(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SSync_Directory(const SSync_Directory& from);
  SSync_Directory(SSync_Directory&& from) noexcept
    : SSync_Directory() {
    *this = ::std::move(from);
  }

  inline SSync_Directory& operator=(const SSync_Directory& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSync_Directory& operator=(SSync_Directory&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SSync_Directory& default_instance() {
    return *internal_default_instance();
  }
  static inline const SSync_Directory* internal_default_instance() {
    return reinterpret_cast<const SSync_Directory*>(
               &_SSync_Directory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SSync_Directory& a, SSync_Directory& b) {
    a.Swap(&b);
  }
  inline void Swap(SSync_Directory* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSync_Directory* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SSync_Directory* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SSync_Directory>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SSync_Directory& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SSync_Directory& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSync_Directory* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SSync.Directory";
  }
  protected:
  explicit SSync_Directory(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSonsFieldNumber = 3,
    kFilesFieldNumber = 4,
    kIdFieldNumber = 1,
    kNameFieldNumber = 2,
  };
  // repeated .SyncCloudDrive.SSync.Directory sons = 3;
  int sons_size() const;
  private:
  int _internal_sons_size() const;
  public:
  void clear_sons();
  ::SyncCloudDrive::SSync_Directory* mutable_sons(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_Directory >*
      mutable_sons();
  private:
  const ::SyncCloudDrive::SSync_Directory& _internal_sons(int index) const;
  ::SyncCloudDrive::SSync_Directory* _internal_add_sons();
  public:
  const ::SyncCloudDrive::SSync_Directory& sons(int index) const;
  ::SyncCloudDrive::SSync_Directory* add_sons();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_Directory >&
      sons() const;

  // repeated .SyncCloudDrive.SSync.File files = 4;
  int files_size() const;
  private:
  int _internal_files_size() const;
  public:
  void clear_files();
  ::SyncCloudDrive::SSync_File* mutable_files(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_File >*
      mutable_files();
  private:
  const ::SyncCloudDrive::SSync_File& _internal_files(int index) const;
  ::SyncCloudDrive::SSync_File* _internal_add_files();
  public:
  const ::SyncCloudDrive::SSync_File& files(int index) const;
  ::SyncCloudDrive::SSync_File* add_files();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_File >&
      files() const;

  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SSync.Directory)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_Directory > sons_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_File > files_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SSync final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SSync) */ {
 public:
  inline SSync() : SSync(nullptr) {}
  ~SSync() override;
  explicit PROTOBUF_CONSTEXPR SSync(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SSync(const SSync& from);
  SSync(SSync&& from) noexcept
    : SSync() {
    *this = ::std::move(from);
  }

  inline SSync& operator=(const SSync& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSync& operator=(SSync&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SSync& default_instance() {
    return *internal_default_instance();
  }
  static inline const SSync* internal_default_instance() {
    return reinterpret_cast<const SSync*>(
               &_SSync_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SSync& a, SSync& b) {
    a.Swap(&b);
  }
  inline void Swap(SSync* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSync* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SSync* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SSync>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SSync& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SSync& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSync* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SSync";
  }
  protected:
  explicit SSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef SSync_File File;
  typedef SSync_Directory Directory;

  // accessors -------------------------------------------------------

  enum : int {
    kRootFieldNumber = 2,
    kStateFieldNumber = 1,
  };
  // .SyncCloudDrive.SSync.Directory root = 2;
  bool has_root() const;
  private:
  bool _internal_has_root() const;
  public:
  void clear_root();
  const ::SyncCloudDrive::SSync_Directory& root() const;
  PROTOBUF_NODISCARD ::SyncCloudDrive::SSync_Directory* release_root();
  ::SyncCloudDrive::SSync_Directory* mutable_root();
  void set_allocated_root(::SyncCloudDrive::SSync_Directory* root);
  private:
  const ::SyncCloudDrive::SSync_Directory& _internal_root() const;
  ::SyncCloudDrive::SSync_Directory* _internal_mutable_root();
  public:
  void unsafe_arena_set_allocated_root(
      ::SyncCloudDrive::SSync_Directory* root);
  ::SyncCloudDrive::SSync_Directory* unsafe_arena_release_root();

  // int32 state = 1;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SSync)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::SyncCloudDrive::SSync_Directory* root_;
  int32_t state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SUploadFile final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SUploadFile) */ {
 public:
  inline SUploadFile() : SUploadFile(nullptr) {}
  ~SUploadFile() override;
  explicit PROTOBUF_CONSTEXPR SUploadFile(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SUploadFile(const SUploadFile& from);
  SUploadFile(SUploadFile&& from) noexcept
    : SUploadFile() {
    *this = ::std::move(from);
  }

  inline SUploadFile& operator=(const SUploadFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline SUploadFile& operator=(SUploadFile&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SUploadFile& default_instance() {
    return *internal_default_instance();
  }
  static inline const SUploadFile* internal_default_instance() {
    return reinterpret_cast<const SUploadFile*>(
               &_SUploadFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(SUploadFile& a, SUploadFile& b) {
    a.Swap(&b);
  }
  inline void Swap(SUploadFile* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SUploadFile* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SUploadFile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SUploadFile>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SUploadFile& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SUploadFile& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SUploadFile* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SUploadFile";
  }
  protected:
  explicit SUploadFile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNoFieldNumber = 1,
    kSlideNoFieldNumber = 2,
  };
  // int32 no = 1;
  void clear_no();
  int32_t no() const;
  void set_no(int32_t value);
  private:
  int32_t _internal_no() const;
  void _internal_set_no(int32_t value);
  public:

  // int32 slide_no = 2;
  void clear_slide_no();
  int32_t slide_no() const;
  void set_slide_no(int32_t value);
  private:
  int32_t _internal_slide_no() const;
  void _internal_set_slide_no(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SUploadFile)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t no_;
  int32_t slide_no_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SDownload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SDownload) */ {
 public:
  inline SDownload() : SDownload(nullptr) {}
  ~SDownload() override;
  explicit PROTOBUF_CONSTEXPR SDownload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SDownload(const SDownload& from);
  SDownload(SDownload&& from) noexcept
    : SDownload() {
    *this = ::std::move(from);
  }

  inline SDownload& operator=(const SDownload& from) {
    CopyFrom(from);
    return *this;
  }
  inline SDownload& operator=(SDownload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SDownload& default_instance() {
    return *internal_default_instance();
  }
  static inline const SDownload* internal_default_instance() {
    return reinterpret_cast<const SDownload*>(
               &_SDownload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(SDownload& a, SDownload& b) {
    a.Swap(&b);
  }
  inline void Swap(SDownload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SDownload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SDownload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SDownload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SDownload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SDownload& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SDownload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SDownload";
  }
  protected:
  explicit SDownload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileIdFieldNumber = 1,
    kDataFieldNumber = 3,
    kSlideNoFieldNumber = 2,
  };
  // string file_id = 1;
  void clear_file_id();
  const std::string& file_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_id();
  PROTOBUF_NODISCARD std::string* release_file_id();
  void set_allocated_file_id(std::string* file_id);
  private:
  const std::string& _internal_file_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_id(const std::string& value);
  std::string* _internal_mutable_file_id();
  public:

  // string data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 slide_no = 2;
  void clear_slide_no();
  int32_t slide_no() const;
  void set_slide_no(int32_t value);
  private:
  int32_t _internal_slide_no() const;
  void _internal_set_slide_no(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SDownload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  int32_t slide_no_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SDeleteFile final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SDeleteFile) */ {
 public:
  inline SDeleteFile() : SDeleteFile(nullptr) {}
  ~SDeleteFile() override;
  explicit PROTOBUF_CONSTEXPR SDeleteFile(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SDeleteFile(const SDeleteFile& from);
  SDeleteFile(SDeleteFile&& from) noexcept
    : SDeleteFile() {
    *this = ::std::move(from);
  }

  inline SDeleteFile& operator=(const SDeleteFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline SDeleteFile& operator=(SDeleteFile&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SDeleteFile& default_instance() {
    return *internal_default_instance();
  }
  static inline const SDeleteFile* internal_default_instance() {
    return reinterpret_cast<const SDeleteFile*>(
               &_SDeleteFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(SDeleteFile& a, SDeleteFile& b) {
    a.Swap(&b);
  }
  inline void Swap(SDeleteFile* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SDeleteFile* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SDeleteFile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SDeleteFile>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SDeleteFile& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SDeleteFile& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SDeleteFile* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SDeleteFile";
  }
  protected:
  explicit SDeleteFile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // int32 state = 1;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SDeleteFile)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SAddDirectory final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SAddDirectory) */ {
 public:
  inline SAddDirectory() : SAddDirectory(nullptr) {}
  ~SAddDirectory() override;
  explicit PROTOBUF_CONSTEXPR SAddDirectory(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SAddDirectory(const SAddDirectory& from);
  SAddDirectory(SAddDirectory&& from) noexcept
    : SAddDirectory() {
    *this = ::std::move(from);
  }

  inline SAddDirectory& operator=(const SAddDirectory& from) {
    CopyFrom(from);
    return *this;
  }
  inline SAddDirectory& operator=(SAddDirectory&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SAddDirectory& default_instance() {
    return *internal_default_instance();
  }
  static inline const SAddDirectory* internal_default_instance() {
    return reinterpret_cast<const SAddDirectory*>(
               &_SAddDirectory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(SAddDirectory& a, SAddDirectory& b) {
    a.Swap(&b);
  }
  inline void Swap(SAddDirectory* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SAddDirectory* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SAddDirectory* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SAddDirectory>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SAddDirectory& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SAddDirectory& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SAddDirectory* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SAddDirectory";
  }
  protected:
  explicit SAddDirectory(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // int32 state = 1;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SAddDirectory)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SDeleteDirectory final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SDeleteDirectory) */ {
 public:
  inline SDeleteDirectory() : SDeleteDirectory(nullptr) {}
  ~SDeleteDirectory() override;
  explicit PROTOBUF_CONSTEXPR SDeleteDirectory(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SDeleteDirectory(const SDeleteDirectory& from);
  SDeleteDirectory(SDeleteDirectory&& from) noexcept
    : SDeleteDirectory() {
    *this = ::std::move(from);
  }

  inline SDeleteDirectory& operator=(const SDeleteDirectory& from) {
    CopyFrom(from);
    return *this;
  }
  inline SDeleteDirectory& operator=(SDeleteDirectory&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SDeleteDirectory& default_instance() {
    return *internal_default_instance();
  }
  static inline const SDeleteDirectory* internal_default_instance() {
    return reinterpret_cast<const SDeleteDirectory*>(
               &_SDeleteDirectory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(SDeleteDirectory& a, SDeleteDirectory& b) {
    a.Swap(&b);
  }
  inline void Swap(SDeleteDirectory* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SDeleteDirectory* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SDeleteDirectory* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SDeleteDirectory>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SDeleteDirectory& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SDeleteDirectory& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SDeleteDirectory* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SDeleteDirectory";
  }
  protected:
  explicit SDeleteDirectory(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // int32 state = 1;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SDeleteDirectory)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// -------------------------------------------------------------------

class SModifyUser final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncCloudDrive.SModifyUser) */ {
 public:
  inline SModifyUser() : SModifyUser(nullptr) {}
  ~SModifyUser() override;
  explicit PROTOBUF_CONSTEXPR SModifyUser(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SModifyUser(const SModifyUser& from);
  SModifyUser(SModifyUser&& from) noexcept
    : SModifyUser() {
    *this = ::std::move(from);
  }

  inline SModifyUser& operator=(const SModifyUser& from) {
    CopyFrom(from);
    return *this;
  }
  inline SModifyUser& operator=(SModifyUser&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SModifyUser& default_instance() {
    return *internal_default_instance();
  }
  static inline const SModifyUser* internal_default_instance() {
    return reinterpret_cast<const SModifyUser*>(
               &_SModifyUser_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(SModifyUser& a, SModifyUser& b) {
    a.Swap(&b);
  }
  inline void Swap(SModifyUser* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SModifyUser* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SModifyUser* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SModifyUser>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SModifyUser& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SModifyUser& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SModifyUser* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncCloudDrive.SModifyUser";
  }
  protected:
  explicit SModifyUser(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
  };
  // int32 state = 1;
  void clear_state();
  int32_t state() const;
  void set_state(int32_t value);
  private:
  int32_t _internal_state() const;
  void _internal_set_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SyncCloudDrive.SModifyUser)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_server_5fto_5fclient_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SRegister

// int32 state = 1;
inline void SRegister::clear_state() {
  state_ = 0;
}
inline int32_t SRegister::_internal_state() const {
  return state_;
}
inline int32_t SRegister::state() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SRegister.state)
  return _internal_state();
}
inline void SRegister::_internal_set_state(int32_t value) {
  
  state_ = value;
}
inline void SRegister::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SRegister.state)
}

// -------------------------------------------------------------------

// SLogin

// int32 state = 1;
inline void SLogin::clear_state() {
  state_ = 0;
}
inline int32_t SLogin::_internal_state() const {
  return state_;
}
inline int32_t SLogin::state() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SLogin.state)
  return _internal_state();
}
inline void SLogin::_internal_set_state(int32_t value) {
  
  state_ = value;
}
inline void SLogin::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SLogin.state)
}

// -------------------------------------------------------------------

// SSync_File

// string id = 1;
inline void SSync_File::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& SSync_File::id() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.File.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SSync_File::set_id(ArgT0&& arg0, ArgT... args) {
 
 id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SSync.File.id)
}
inline std::string* SSync_File::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SSync.File.id)
  return _s;
}
inline const std::string& SSync_File::_internal_id() const {
  return id_.Get();
}
inline void SSync_File::_internal_set_id(const std::string& value) {
  
  id_.Set(value, GetArenaForAllocation());
}
inline std::string* SSync_File::_internal_mutable_id() {
  
  return id_.Mutable(GetArenaForAllocation());
}
inline std::string* SSync_File::release_id() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.SSync.File.id)
  return id_.Release();
}
inline void SSync_File::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (id_.IsDefault()) {
    id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.SSync.File.id)
}

// string name = 2;
inline void SSync_File::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& SSync_File::name() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.File.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SSync_File::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SSync.File.name)
}
inline std::string* SSync_File::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SSync.File.name)
  return _s;
}
inline const std::string& SSync_File::_internal_name() const {
  return name_.Get();
}
inline void SSync_File::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* SSync_File::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* SSync_File::release_name() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.SSync.File.name)
  return name_.Release();
}
inline void SSync_File::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.SSync.File.name)
}

// string md5 = 3;
inline void SSync_File::clear_md5() {
  md5_.ClearToEmpty();
}
inline const std::string& SSync_File::md5() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.File.md5)
  return _internal_md5();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SSync_File::set_md5(ArgT0&& arg0, ArgT... args) {
 
 md5_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SSync.File.md5)
}
inline std::string* SSync_File::mutable_md5() {
  std::string* _s = _internal_mutable_md5();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SSync.File.md5)
  return _s;
}
inline const std::string& SSync_File::_internal_md5() const {
  return md5_.Get();
}
inline void SSync_File::_internal_set_md5(const std::string& value) {
  
  md5_.Set(value, GetArenaForAllocation());
}
inline std::string* SSync_File::_internal_mutable_md5() {
  
  return md5_.Mutable(GetArenaForAllocation());
}
inline std::string* SSync_File::release_md5() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.SSync.File.md5)
  return md5_.Release();
}
inline void SSync_File::set_allocated_md5(std::string* md5) {
  if (md5 != nullptr) {
    
  } else {
    
  }
  md5_.SetAllocated(md5, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (md5_.IsDefault()) {
    md5_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.SSync.File.md5)
}

// -------------------------------------------------------------------

// SSync_Directory

// string id = 1;
inline void SSync_Directory::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& SSync_Directory::id() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.Directory.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SSync_Directory::set_id(ArgT0&& arg0, ArgT... args) {
 
 id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SSync.Directory.id)
}
inline std::string* SSync_Directory::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SSync.Directory.id)
  return _s;
}
inline const std::string& SSync_Directory::_internal_id() const {
  return id_.Get();
}
inline void SSync_Directory::_internal_set_id(const std::string& value) {
  
  id_.Set(value, GetArenaForAllocation());
}
inline std::string* SSync_Directory::_internal_mutable_id() {
  
  return id_.Mutable(GetArenaForAllocation());
}
inline std::string* SSync_Directory::release_id() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.SSync.Directory.id)
  return id_.Release();
}
inline void SSync_Directory::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (id_.IsDefault()) {
    id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.SSync.Directory.id)
}

// string name = 2;
inline void SSync_Directory::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& SSync_Directory::name() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.Directory.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SSync_Directory::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SSync.Directory.name)
}
inline std::string* SSync_Directory::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SSync.Directory.name)
  return _s;
}
inline const std::string& SSync_Directory::_internal_name() const {
  return name_.Get();
}
inline void SSync_Directory::_internal_set_name(const std::string& value) {
  
  name_.Set(value, GetArenaForAllocation());
}
inline std::string* SSync_Directory::_internal_mutable_name() {
  
  return name_.Mutable(GetArenaForAllocation());
}
inline std::string* SSync_Directory::release_name() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.SSync.Directory.name)
  return name_.Release();
}
inline void SSync_Directory::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault()) {
    name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.SSync.Directory.name)
}

// repeated .SyncCloudDrive.SSync.Directory sons = 3;
inline int SSync_Directory::_internal_sons_size() const {
  return sons_.size();
}
inline int SSync_Directory::sons_size() const {
  return _internal_sons_size();
}
inline void SSync_Directory::clear_sons() {
  sons_.Clear();
}
inline ::SyncCloudDrive::SSync_Directory* SSync_Directory::mutable_sons(int index) {
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SSync.Directory.sons)
  return sons_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_Directory >*
SSync_Directory::mutable_sons() {
  // @@protoc_insertion_point(field_mutable_list:SyncCloudDrive.SSync.Directory.sons)
  return &sons_;
}
inline const ::SyncCloudDrive::SSync_Directory& SSync_Directory::_internal_sons(int index) const {
  return sons_.Get(index);
}
inline const ::SyncCloudDrive::SSync_Directory& SSync_Directory::sons(int index) const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.Directory.sons)
  return _internal_sons(index);
}
inline ::SyncCloudDrive::SSync_Directory* SSync_Directory::_internal_add_sons() {
  return sons_.Add();
}
inline ::SyncCloudDrive::SSync_Directory* SSync_Directory::add_sons() {
  ::SyncCloudDrive::SSync_Directory* _add = _internal_add_sons();
  // @@protoc_insertion_point(field_add:SyncCloudDrive.SSync.Directory.sons)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_Directory >&
SSync_Directory::sons() const {
  // @@protoc_insertion_point(field_list:SyncCloudDrive.SSync.Directory.sons)
  return sons_;
}

// repeated .SyncCloudDrive.SSync.File files = 4;
inline int SSync_Directory::_internal_files_size() const {
  return files_.size();
}
inline int SSync_Directory::files_size() const {
  return _internal_files_size();
}
inline void SSync_Directory::clear_files() {
  files_.Clear();
}
inline ::SyncCloudDrive::SSync_File* SSync_Directory::mutable_files(int index) {
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SSync.Directory.files)
  return files_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_File >*
SSync_Directory::mutable_files() {
  // @@protoc_insertion_point(field_mutable_list:SyncCloudDrive.SSync.Directory.files)
  return &files_;
}
inline const ::SyncCloudDrive::SSync_File& SSync_Directory::_internal_files(int index) const {
  return files_.Get(index);
}
inline const ::SyncCloudDrive::SSync_File& SSync_Directory::files(int index) const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.Directory.files)
  return _internal_files(index);
}
inline ::SyncCloudDrive::SSync_File* SSync_Directory::_internal_add_files() {
  return files_.Add();
}
inline ::SyncCloudDrive::SSync_File* SSync_Directory::add_files() {
  ::SyncCloudDrive::SSync_File* _add = _internal_add_files();
  // @@protoc_insertion_point(field_add:SyncCloudDrive.SSync.Directory.files)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::SyncCloudDrive::SSync_File >&
SSync_Directory::files() const {
  // @@protoc_insertion_point(field_list:SyncCloudDrive.SSync.Directory.files)
  return files_;
}

// -------------------------------------------------------------------

// SSync

// int32 state = 1;
inline void SSync::clear_state() {
  state_ = 0;
}
inline int32_t SSync::_internal_state() const {
  return state_;
}
inline int32_t SSync::state() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.state)
  return _internal_state();
}
inline void SSync::_internal_set_state(int32_t value) {
  
  state_ = value;
}
inline void SSync::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SSync.state)
}

// .SyncCloudDrive.SSync.Directory root = 2;
inline bool SSync::_internal_has_root() const {
  return this != internal_default_instance() && root_ != nullptr;
}
inline bool SSync::has_root() const {
  return _internal_has_root();
}
inline void SSync::clear_root() {
  if (GetArenaForAllocation() == nullptr && root_ != nullptr) {
    delete root_;
  }
  root_ = nullptr;
}
inline const ::SyncCloudDrive::SSync_Directory& SSync::_internal_root() const {
  const ::SyncCloudDrive::SSync_Directory* p = root_;
  return p != nullptr ? *p : reinterpret_cast<const ::SyncCloudDrive::SSync_Directory&>(
      ::SyncCloudDrive::_SSync_Directory_default_instance_);
}
inline const ::SyncCloudDrive::SSync_Directory& SSync::root() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SSync.root)
  return _internal_root();
}
inline void SSync::unsafe_arena_set_allocated_root(
    ::SyncCloudDrive::SSync_Directory* root) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(root_);
  }
  root_ = root;
  if (root) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SyncCloudDrive.SSync.root)
}
inline ::SyncCloudDrive::SSync_Directory* SSync::release_root() {
  
  ::SyncCloudDrive::SSync_Directory* temp = root_;
  root_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::SyncCloudDrive::SSync_Directory* SSync::unsafe_arena_release_root() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.SSync.root)
  
  ::SyncCloudDrive::SSync_Directory* temp = root_;
  root_ = nullptr;
  return temp;
}
inline ::SyncCloudDrive::SSync_Directory* SSync::_internal_mutable_root() {
  
  if (root_ == nullptr) {
    auto* p = CreateMaybeMessage<::SyncCloudDrive::SSync_Directory>(GetArenaForAllocation());
    root_ = p;
  }
  return root_;
}
inline ::SyncCloudDrive::SSync_Directory* SSync::mutable_root() {
  ::SyncCloudDrive::SSync_Directory* _msg = _internal_mutable_root();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SSync.root)
  return _msg;
}
inline void SSync::set_allocated_root(::SyncCloudDrive::SSync_Directory* root) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete root_;
  }
  if (root) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(root);
    if (message_arena != submessage_arena) {
      root = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, root, submessage_arena);
    }
    
  } else {
    
  }
  root_ = root;
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.SSync.root)
}

// -------------------------------------------------------------------

// SUploadFile

// int32 no = 1;
inline void SUploadFile::clear_no() {
  no_ = 0;
}
inline int32_t SUploadFile::_internal_no() const {
  return no_;
}
inline int32_t SUploadFile::no() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SUploadFile.no)
  return _internal_no();
}
inline void SUploadFile::_internal_set_no(int32_t value) {
  
  no_ = value;
}
inline void SUploadFile::set_no(int32_t value) {
  _internal_set_no(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SUploadFile.no)
}

// int32 slide_no = 2;
inline void SUploadFile::clear_slide_no() {
  slide_no_ = 0;
}
inline int32_t SUploadFile::_internal_slide_no() const {
  return slide_no_;
}
inline int32_t SUploadFile::slide_no() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SUploadFile.slide_no)
  return _internal_slide_no();
}
inline void SUploadFile::_internal_set_slide_no(int32_t value) {
  
  slide_no_ = value;
}
inline void SUploadFile::set_slide_no(int32_t value) {
  _internal_set_slide_no(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SUploadFile.slide_no)
}

// -------------------------------------------------------------------

// SDownload

// string file_id = 1;
inline void SDownload::clear_file_id() {
  file_id_.ClearToEmpty();
}
inline const std::string& SDownload::file_id() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SDownload.file_id)
  return _internal_file_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SDownload::set_file_id(ArgT0&& arg0, ArgT... args) {
 
 file_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SDownload.file_id)
}
inline std::string* SDownload::mutable_file_id() {
  std::string* _s = _internal_mutable_file_id();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SDownload.file_id)
  return _s;
}
inline const std::string& SDownload::_internal_file_id() const {
  return file_id_.Get();
}
inline void SDownload::_internal_set_file_id(const std::string& value) {
  
  file_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SDownload::_internal_mutable_file_id() {
  
  return file_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SDownload::release_file_id() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.SDownload.file_id)
  return file_id_.Release();
}
inline void SDownload::set_allocated_file_id(std::string* file_id) {
  if (file_id != nullptr) {
    
  } else {
    
  }
  file_id_.SetAllocated(file_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (file_id_.IsDefault()) {
    file_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.SDownload.file_id)
}

// int32 slide_no = 2;
inline void SDownload::clear_slide_no() {
  slide_no_ = 0;
}
inline int32_t SDownload::_internal_slide_no() const {
  return slide_no_;
}
inline int32_t SDownload::slide_no() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SDownload.slide_no)
  return _internal_slide_no();
}
inline void SDownload::_internal_set_slide_no(int32_t value) {
  
  slide_no_ = value;
}
inline void SDownload::set_slide_no(int32_t value) {
  _internal_set_slide_no(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SDownload.slide_no)
}

// string data = 3;
inline void SDownload::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& SDownload::data() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SDownload.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SDownload::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SDownload.data)
}
inline std::string* SDownload::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:SyncCloudDrive.SDownload.data)
  return _s;
}
inline const std::string& SDownload::_internal_data() const {
  return data_.Get();
}
inline void SDownload::_internal_set_data(const std::string& value) {
  
  data_.Set(value, GetArenaForAllocation());
}
inline std::string* SDownload::_internal_mutable_data() {
  
  return data_.Mutable(GetArenaForAllocation());
}
inline std::string* SDownload::release_data() {
  // @@protoc_insertion_point(field_release:SyncCloudDrive.SDownload.data)
  return data_.Release();
}
inline void SDownload::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault()) {
    data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SyncCloudDrive.SDownload.data)
}

// -------------------------------------------------------------------

// SDeleteFile

// int32 state = 1;
inline void SDeleteFile::clear_state() {
  state_ = 0;
}
inline int32_t SDeleteFile::_internal_state() const {
  return state_;
}
inline int32_t SDeleteFile::state() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SDeleteFile.state)
  return _internal_state();
}
inline void SDeleteFile::_internal_set_state(int32_t value) {
  
  state_ = value;
}
inline void SDeleteFile::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SDeleteFile.state)
}

// -------------------------------------------------------------------

// SAddDirectory

// int32 state = 1;
inline void SAddDirectory::clear_state() {
  state_ = 0;
}
inline int32_t SAddDirectory::_internal_state() const {
  return state_;
}
inline int32_t SAddDirectory::state() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SAddDirectory.state)
  return _internal_state();
}
inline void SAddDirectory::_internal_set_state(int32_t value) {
  
  state_ = value;
}
inline void SAddDirectory::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SAddDirectory.state)
}

// -------------------------------------------------------------------

// SDeleteDirectory

// int32 state = 1;
inline void SDeleteDirectory::clear_state() {
  state_ = 0;
}
inline int32_t SDeleteDirectory::_internal_state() const {
  return state_;
}
inline int32_t SDeleteDirectory::state() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SDeleteDirectory.state)
  return _internal_state();
}
inline void SDeleteDirectory::_internal_set_state(int32_t value) {
  
  state_ = value;
}
inline void SDeleteDirectory::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SDeleteDirectory.state)
}

// -------------------------------------------------------------------

// SModifyUser

// int32 state = 1;
inline void SModifyUser::clear_state() {
  state_ = 0;
}
inline int32_t SModifyUser::_internal_state() const {
  return state_;
}
inline int32_t SModifyUser::state() const {
  // @@protoc_insertion_point(field_get:SyncCloudDrive.SModifyUser.state)
  return _internal_state();
}
inline void SModifyUser::_internal_set_state(int32_t value) {
  
  state_ = value;
}
inline void SModifyUser::set_state(int32_t value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:SyncCloudDrive.SModifyUser.state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SyncCloudDrive

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::SyncCloudDrive::ServerCommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SyncCloudDrive::ServerCommandType>() {
  return ::SyncCloudDrive::ServerCommandType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_server_5fto_5fclient_2eproto
